// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_airfoildialog.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_qcustomplot.cpp"
#include "EWIEGA46WW/moc_settingsdialog.cpp"
